pipeline {
    agent {
        docker {
            image 'sed5-s2/jenkins:0.0.1'
        }
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'beta', url: 'https://github.com/robertmrb/sed5-s2.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    docker.build("loadbalancer:0.0.2", "./apps/loadbalancer")
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                script {
                    withDockerRegistry(credentialsId: '3f1823a2-6ec9-4d97-9725-0f0670d25b9c', url: 'https://index.docker.io/v1/') {
                         docker.build('robertmrb/loadbalancer:0.0.2').push()
                    }
                }
            }
        }
    }
}
