pipeline {
    agent {
        docker {
            image 'sed5-s2/jenkins:0.0.1'
        }
    }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'beta', url: 'https://github.com/robertmrb/sed5-s2.git'
            }
        }
        stage('Build images') {
            steps {
                sh 'docker build --no-cache --progress=plain --tag sed5-s2/loadbalancer:0.0.2 -f ./apps/loadbalancer/dockerfile .'
            }
        }
    }
}
